# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Image on scalar regression
#' @description
#' Scalar on Image regression using the sparse-mean prior
#' @name Image_on_scalar
#' @param y outcome
#' @param X vector covariate
#' @param M Matrix of functional images
#' @param lambda thresholding parameter
#' @param rho scaling parameter in CAR model
#' @param B matrix of covariance neighborhood
#' @param in_Sigma_inv
#' @param in_D
#' @param init_paras
#' @param batch_control
#' @param method
#' @useDynLib STCAR, .registration=TRUE
#' @export
IonS_CAVI_rho <- function(M, X, C, lambda, basis, rho, B, W, in_Sigma_inv, in_D, method, init_paras, sigmasq_step_controls, in_delta_rho, SGD_controls, initial_sigma_sq = 1, initial_tau_mu_sq = 0.01, initial_sigma_alpha_sq = 1, initial_sigma_zeta_sq = 1, initial_sigma_eta_sq = 1, eta_freq = 1L, max_iter = 1000L, mcmc_sample = 1000L, burnin = 1000L, thinning = 1L, begin_f_alpha = 0L, f_alpha_interval = 1L, paras_diff_tol = 1e-6, verbose = 5000L, save_profile = 1L, display_progress = FALSE) {
    .Call('_STCAR_IonS_CAVI_rho', PACKAGE = 'STCAR', M, X, C, lambda, basis, rho, B, W, in_Sigma_inv, in_D, method, init_paras, sigmasq_step_controls, in_delta_rho, SGD_controls, initial_sigma_sq, initial_tau_mu_sq, initial_sigma_alpha_sq, initial_sigma_zeta_sq, initial_sigma_eta_sq, eta_freq, max_iter, mcmc_sample, burnin, thinning, begin_f_alpha, f_alpha_interval, paras_diff_tol, verbose, save_profile, display_progress)
}

geweke_test <- function(x, p_thresh = 0.05, frac1 = 0.1, frac2 = 0.5) {
    .Call('_STCAR_geweke_test', PACKAGE = 'STCAR', x, p_thresh, frac1, frac2)
}

complement <- function(start, end, n) {
    .Call('_STCAR_complement', PACKAGE = 'STCAR', start, end, n)
}

High_to_low_vec <- function(High_vec, L, Phi_Q, region_idx, L_idx) {
    .Call('_STCAR_High_to_low_vec', PACKAGE = 'STCAR', High_vec, L, Phi_Q, region_idx, L_idx)
}

High_to_low <- function(High_mat, L, Phi_Q, region_idx, L_idx) {
    .Call('_STCAR_High_to_low', PACKAGE = 'STCAR', High_mat, L, Phi_Q, region_idx, L_idx)
}

Low_to_high <- function(Low_mat, p, Phi_Q, region_idx, L_idx) {
    .Call('_STCAR_Low_to_high', PACKAGE = 'STCAR', Low_mat, p, Phi_Q, region_idx, L_idx)
}

Low_to_high_vec <- function(Low_vec, p, Phi_Q, region_idx, L_idx) {
    .Call('_STCAR_Low_to_high_vec', PACKAGE = 'STCAR', Low_vec, p, Phi_Q, region_idx, L_idx)
}

sample_truncated_normal_vec <- function(mu, sigma, lambda, delta) {
    .Call('_STCAR_sample_truncated_normal_vec', PACKAGE = 'STCAR', mu, sigma, lambda, delta)
}

truncated_normal_stats_vec <- function(mu, sigma, lambda, delta, output) {
    .Call('_STCAR_truncated_normal_stats_vec', PACKAGE = 'STCAR', mu, sigma, lambda, delta, output)
}

#' @title Scalar on Image regression standalone
#' @description
#' Scalar on Image regression using the sparse-mean prior
#' @name Scalar_on_Image
#' @param y outcome
#' @param X vector covariate
#' @param M Matrix of functional images
#' @param lambda thresholding parameter
#' @param rho scaling parameter in CAR model
#' @param B matrix of covariance neighborhood
#' @param in_Sigma_inv
#' @param in_D
#' @param init_paras
#' @param method
#' @import Rcpp
#' @useDynLib STCAR, .registration=TRUE
#' @export
#' [[Rcpp::export(rng = false)]]
NULL

